@startuml alternative context diagram AgroTech

' Задаем стиль
!NEW_C4_STYLE=1
!theme C4_violet from ../C4-PlantUML/themes

' Импортируем элементы
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include ../C4-PlantUML/C4_Context.puml

' Определяем акторов


Enterprise_Boundary(farm, "Ферма"){
    Person(operator, "Оператор", "Сотрудник на ферме")
    System(edge_control, "Управление edge-устройствами", "Анализирует полученные данные с IoT устройств, управляет ими")
    System_Ext(edge_device, "Edge-устройство", "Различные IoT датчики и пульты управления оборудованием")
    System_Ext(vid_mon, "Система видеорегистрации", "Точка сбора видеопотоков с камер")
    System(farm_broker, "Брокер", "Точка сбора метрик и уведомлений")
    System(farm_notification, "Отправка уведомлений", "Служит для отправки уведомлений")
    System(farm_sms, "СМС-шлюз", "Служит для отправки уведомлений")
}

Enterprise_Boundary(center, "Центральный узел") {
    Person(duty, "Дежурная смена", "Состоит из отдельного персонала или дежурных админов и разработчиков")
    System(global_broker, "Брокер", "Точка сбора метрик и уведомлений")
    System(apm, "APM-система", "Собирает метрики, фиксирует аварии, уведомляет")
    System(scheduling, "Управление расписанием", "API для формирования расписания устройств")
    System(vid_mon_anal, "Анализ данных с видеомониторинга", "Обрабатывает потоки видео с камер с помощью ИИ")
}
System_Ext(existing_system, "Общая система предприятия")

' Рисуем связи

' В пределах фермы

Rel(edge_control, edge_device, "Управляет устройствами")
Rel(edge_device, farm_broker, "Передает метрики")
Rel(edge_control, farm_broker, "Передает уведомления")

Rel(farm_notification, operator, "Отправляет уведомления по edge-устройствам, анализу видео")
Rel(farm_notification, farm_broker, "Получает уведомления для отправки")

Rel(farm_notification, farm_sms, "Отправляет уведомления по edge-устройствам, анализу видео")
Rel(farm_sms, operator, "Отправляет уведомления по edge-устройствам, анализу видео")


' Между фермой и цетральным сервером
Rel(farm_broker, global_broker, "Синхронизируют уведомления, метрики, расписание")
Rel(duty, scheduling, "Задает расписание")
Rel(farm_sms, duty, "Отправляет уведомления по edge-устройствам, анализу видео")
Rel(vid_mon, vid_mon_anal, "Передает потоки видео")
Rel(vid_mon_anal, global_broker, "Передает метрики и уведомления")
' В пределах центрального сервера

Rel(apm, global_broker, "Обрабатывает уведомления и метрики")
Rel(apm, duty, "Отправляет уведомления")
Rel(scheduling, global_broker, "Отправляет события об изменении расписания")

' Между центральным сервером и общей системой предприятия
Rel(global_broker, existing_system, "Передает метрики и уведомления в имеющиеся хранилища")

@enduml
