@startuml alternative container diagram AgroTech

' Задаем стиль
!NEW_C4_STYLE=1
!theme C4_violet from ../C4-PlantUML/themes

' Импортируем элементы
!include ../C4-PlantUML/C4_Container.puml

' Определяем акторов

Enterprise_Boundary(farm, "Ферма"){
    System(farm_broker, "RabbitMQ", "Точка сбора метрик, событий и уведомлений")
    Person(operator, "Оператор", "Сотрудник на ферме")
    System_Boundary(edge_control, "Управление edge-устройствами"){
        Container(edge_control_api, "API", "Go", "управление edge-устройствами")
        ContainerDb(edge_control_db, "СУБД", "Postgres")
    }
    System_Ext(edge_device, "Edge-устройство", "Различные IoT датчики и пульты управления оборудованием")
    System_Ext(vid_mon, "Система видеорегистрации", "Точка сбора видеопотоков с камер")
    System_Boundary(vid_mon_anal, "Анализ данных с видеомониторинга"){
        Container(ai, "Видеоаналитика ИИ", "Python/C/C++", "API для видеопотоков, Анализ видеопотоков с помощью ИИ")
    }
    System_Boundary(notification, "Отправка уведомлений"){
        Container(notification_sender, "Обработчик уведомлений", "Python", "Читает уведомления из брокера и перенаправляет нужному адресату. Отправлляет СМС.")
    }

    System(farm_sms, "СМС-шлюз", "Служит для отправки уведомлений")

}
Enterprise_Boundary(center, "Центральный узел") {
    Person(duty, "Дежурная смена", "Состоит из отдельного персонала или дежурных админов и разработчиков")
    System(global_broker, "Kafka", "Точка сбора метрик и уведомлений")
    System(apm, "APM-система", "Собирает метрики, фиксирует аварии, уведомляет")
    System_Boundary(scheduler, "Расписание"){
        Container(schedule_api, "API расписаний", "Python FastAPI", "API для управления расписанием")
    }

}
System_Ext(existing_system, "Общая система предприятия")

' Рисуем связи

' В пределах фермы
Rel(ai, vid_mon, "Получает видеопотоки", "ONVIF")
Rel(ai, farm_broker, "Отправляет события и метрики, Читает изменения в расписании", "AMQP")

Rel(notification_sender, farm_broker, "Читает события и метрики", "AMQP")
Rel(notification_sender, operator, "Отправляет уведомления", "HTTPS (Websocket)")
Rel(notification_sender, farm_sms, "Отправляет уведомления средством", "HTTPS")
Rel(farm_sms, operator, "Отправляет уведомления по edge-устройствам, анализу видео", "SMS")

Rel(edge_control_api, farm_broker, "Отправляет события, следит за изменением расписания", "AMQP")
Rel(edge_control_api, edge_control_db, "Хранит информацию об edge-устройствах")

Rel(edge_control_api, edge_device, "Отправляет управляющие команды", "HTTPS")
Rel(duty, schedule_api, "Управляет расписанием")


' Между фермой и цетральным сервером

Rel(farm_broker, global_broker, "Синхронизирует события", "AMQP")
Rel(apm, global_broker, "Собирает и обрабатывает уведомления и метрики")
Rel(apm, duty, "Отправляет уведомления")
Rel(farm_sms, duty, "Отправляет уведомления по edge-устройствам, анализу видео", "SMS")
Rel(schedule_api, global_broker, "Отправляет изменения в расписании", "AMQP")

' Между центральным сервером и общей системой предприятия
Rel(global_broker, existing_system, "Передает метрики и уведомления в имеющиеся хранилища")
