@startuml main container diagram AgroTech

' Задаем стиль
!NEW_C4_STYLE=1
!theme C4_violet from ../C4-PlantUML/themes

' Импортируем элементы
!include ../C4-PlantUML/C4_Container.puml

' Определяем акторов
' Для отправки метрик с iot можно использовать MQTT. А значит можно слать сразу в брокер. Переделать выделив отдельно брокер в c4 и c3
Enterprise_Boundary(farm, "Ферма"){
    System(farm_broker, "RabbitMQ", "Точка сбора метрик, событий и уведомлений")
    Person(operator, "Оператор", "Сотрудник на ферме")
    System_Boundary(edge_control, "Управление edge-устройствами"){
        Container(edge_control_api, "API", "Go", "управление edge-устройствами")
    }
    System_Ext(edge_device, "Edge-устройство", "Различные IoT датчики и пульты управления оборудованием")
    System_Ext(vid_mon, "Система видеорегистрации", "Точка сбора видеопотоков с камер")
    System_Boundary(vid_mon_anal, "Анализ данных с видеомониторинга"){
        ' TODO: выбрать технологии позже
        Container(ai, "Видеоаналитика ИИ", "Python FastAPI", "API для видеопотоков, Анализ видеопотоков с помощью ИИ")
    }
    System_Boundary(notification, "Отправка уведомлений"){
        Container(notification_worker, "Воркер уведомлений", "Python", "Читает уведомления из брокера и перенаправляет нужному адресату. Отправлляет СМС.")
    }
    System_Boundary(scheduler, "Расписание"){
        Container(scheduler_api, "API расписаний", "Python FastAPI", "API для управления расписанием")
    }

}
Enterprise_Boundary(center, "Центральный узел") {
    Person(duty, "Дежурная смена", "Состоит из отдельного персонала или дежурных админов и разработчиков")
    Person(analyst, "Аналитик данных")
    System(global_broker, "Kafka", "Точка сбора метрик и уведомлений")
    System(apm, "APM-система", "Собирает метрики, фиксирует аварии, уведомляет")

}
System_Ext(existing_system, "Общая система предприятия")

' Рисуем связи

' В пределах фермы
Rel(ai, vid_mon, "Получает видеопотоки", "ONVIF")
Rel(ai, farm_broker, "Отправляет события и метрики, Читает изменения в расписании", "AMQP")

Rel(notification_worker, farm_broker, "Читает события и метрики", "AMQP")
Rel(notification_worker, operator, "Отправляет уведомления", "HTTPS (Websocket)")

Rel(edge_control_api, farm_broker, "Отправляет события, следит за изменением расписания", "AMQP")
Rel(edge_control_api, edge_device, "Отправляет управляющие команды", "HTTPS")
Rel(duty, scheduler_api, "Управляет расписанием")
Rel(scheduler_api, farm_broker, "Отправляет изменения в расписании", "AMQP")


' Между фермой и цетральным сервером

Rel(farm_broker, global_broker, "Отправляет все события в глобальный брокер", "AMQP")
Rel(apm, global_broker, "Собирает и обрабатывает уведомления и метрики")
Rel(apm, duty, "Отправляет уведомления")

Rel(analyst, apm, "Проводит аналитику полученных данных от ферм")

' Между центральным сервером и общей системой предприятия
Rel(global_broker, existing_system, "Передает метрики и уведомления в имеющиеся хранилища")
